# Random Forest
Random forest is a machine learning algorith that uses many trees to make better predictions. It can be used for classification and regression problems..

## Random Forest Classifier

In [94]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,classification_report
from sklearn.model_selection import train_test_split
import seaborn as sns

### Load the dataset

In [95]:
titanic = sns.load_dataset("titanic")

## Explore the dataset

In [96]:
titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [97]:
titanic.shape

(891, 15)

In [98]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [99]:
gender = {"male":0,"female":1}

In [100]:
titanic.describe().T

          count       mean        std   min      25%      50%   75%       max
survived  891.0   0.383838   0.486592  0.00   0.0000   0.0000   1.0    1.0000
pclass    891.0   2.308642   0.836071  1.00   2.0000   3.0000   3.0    3.0000
age       714.0  29.699118  14.526497  0.42  20.1250  28.0000  38.0   80.0000
sibsp     891.0   0.523008   1.102743  0.00   0.0000   0.0000   1.0    8.0000
parch     891.0   0.381594   0.806057  0.00   0.0000   0.0000   0.0    6.0000
fare      891.0  32.204208  49.693429  0.00   7.9104  14.4542  31.0  512.3292

In [101]:
titanic = titanic.dropna(subset=["survived"])

### Handle the missing values

In [102]:
titanic["sex"] = titanic.sex.map(gender)

In [103]:
titanic["age"] = titanic.age.fillna(titanic.age.median())

In [104]:
titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,0,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,1,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,1,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,1,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,0,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [105]:
titanic.isnull().sum()

survived         0
pclass           0
sex              0
age              0
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

### Determine the X-features and the target

In [106]:
features = ["pclass","sex","age","sibsp","parch","fare"]

In [107]:
X = titanic[features]
y = titanic["survived"]
X.shape,y.shape

((891, 6), (891,))

### Split the data into train and test

In [108]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state = 42)

### Create the model

In [109]:
rf_classifier = RandomForestClassifier(n_estimators = 100,random_state = 42)
rf_classifier.fit(X_train,y_train)

RandomForestClassifier(random_state=42)

### Make predictions

In [110]:
y_pred = rf_classifier.predict(X_test)

### Evaluation

In [111]:
accuracy = accuracy_score(y_test,y_pred)
print(f"Accuracy of the model : ",accuracy)

Accuracy of the model :  0.8044692737430168

In [112]:
report = classification_report(y_test,y_pred)
report

'              precision    recall  f1-score   support\n\n           0       0.82      0.86      0.84       105\n           1       0.78      0.73      0.76        74\n\n    accuracy                           0.80       179\n   macro avg       0.80      0.79      0.80       179\nweighted avg       0.80      0.80      0.80       179\n'

In [113]:
sample = X_test.iloc[:1]
sample

     pclass  sex   age  sibsp  parch     fare
709       3    0  28.0      1      1  15.2458

In [114]:
prediction = rf_classifier.predict(sample)
prediction

array([0])

## What would happen if we change the hyperparameters

In [115]:
def Random_forest_hyper(X_train,X_test,y_train,y_test,max_depth):
    model = RandomForestClassifier(n_estimators = 100,random_state = 42,max_depth = max_depth)
    model.fit(X_train,y_train)
    y_preds = model.predict(X_test)

    accuracy = accuracy_score(y_test,y_preds)
    print(f"Accuracy : ",accuracy)
    report = classification_report(y_test,y_preds)
    print(f"Classification Report : ",classification_report)

In [116]:
depths = [25,50,100]
for depth in depths:
    Random_forest_hyper(X_train,X_test,y_train,y_test,max_depth = depth)

Accuracy :  0.8044692737430168
Classification Report :  <function classification_report at 0x000001E1B59F5A80>
Accuracy :  0.8044692737430168
Classification Report :  <function classification_report at 0x000001E1B59F5A80>
Accuracy :  0.8044692737430168
Classification Report :  <function classification_report at 0x000001E1B59F5A80>

## Random Forest Regression

In [117]:
import pandas as pd
from sklearn.datasets import fetch_california_housing
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error,r2_score

In [118]:
california_housing = fetch_california_housing(as_frame = True).frame
california_housing

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedHouseVal
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422
...,...,...,...,...,...,...,...,...,...
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09,0.781
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21,0.771
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22,0.923
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32,0.847
20639,2.3886,16.0,5.254717,1.162264,1387.0,2.616981,39.37,-121.24,0.894

In [119]:
california_housing.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   MedInc       20640 non-null  float64
 1   HouseAge     20640 non-null  float64
 2   AveRooms     20640 non-null  float64
 3   AveBedrms    20640 non-null  float64
 4   Population   20640 non-null  float64
 5   AveOccup     20640 non-null  float64
 6   Latitude     20640 non-null  float64
 7   Longitude    20640 non-null  float64
 8   MedHouseVal  20640 non-null  float64
dtypes: float64(9)
memory usage: 1.4 MB

In [120]:
california_housing.describe()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedHouseVal
count,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000
mean,3.870671,28.639486,5.429000,1.096675,1425.476744,3.070655,35.631861,-119.569704,2.068558
std,1.899822,12.585558,2.474173,0.473911,1132.462122,10.386050,2.135952,2.003532,1.153956
min,0.499900,1.000000,0.846154,0.333333,3.000000,0.692308,32.540000,-124.350000,0.149990
25%,2.563400,18.000000,4.440716,1.006079,787.000000,2.429741,33.930000,-121.800000,1.196000
50%,3.534800,29.000000,5.229129,1.048780,1166.000000,2.818116,34.260000,-118.490000,1.797000
75%,4.743250,37.000000,6.052381,1.099526,1725.000000,3.282261,37.710000,-118.010000,2.647250
max,15.000100,52.000000,141.909091,34.066667,35682.000000,1243.333333,41.950000,-114.310000,5.000010

In [121]:
california_housing.isnull().sum()

MedInc         0
HouseAge       0
AveRooms       0
AveBedrms      0
Population     0
AveOccup       0
Latitude       0
Longitude      0
MedHouseVal    0
dtype: int64

In [122]:
X = california_housing.drop(columns = ["MedHouseVal"])
y = california_housing.MedHouseVal

In [123]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state = 42)

In [124]:
rf_regressor = RandomForestRegressor(n_estimators = 100,random_state = 42)
rf_regressor.fit(X_train,y_train)

RandomForestRegressor(random_state=42)

In [125]:
preds = rf_regressor.predict(X_test)
mse = mean_squared_error(y_test,preds)
r2 = r2_score(y_test,preds)
print(f"Mean Squared error of the model : ",mse)
print(f"R2 score of the model : ",r2)

Mean Squared error of the model :  0.2553684927247781
R2 score of the model :  0.8051230593157366

In [127]:
sample = X_test[:1]
sample

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
20046,1.6812,25.0,4.192201,1.022284,1392.0,3.877437,36.06,-119.01

In [128]:
rf_regressor.predict(sample)

array([0.5095])

In [129]:
preds[0]

np.float64(0.5094999999999998)